### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by themalkolm**
Yaw, automatic builds. Good starting point.

So much here, I don't know where to even start.

* vagrant configuration
* travis configuration
* makefiles (note that now we download our own glade and install go-bindata for every build)
* updated README.md

### CODE REVIEW

**Comment by themalkolm** [comment]
Please register this project in travis under your name and enable building for pull requests. It should pick this commit right away. This way we can confirm it actually builds :)

**Comment by themalkolm** [comment]
If it doesn't pick it, I can resubmit pull request after you switched it on. I think it is enabled by default.

**Comment by iverberk** [comment]
Ok, enabling it now, hold on.

**Comment by themalkolm** [comment]
@iverberk kk, tell me when it is on. Will squash another commit that enables glide provisioning as well.

**Comment by iverberk** [comment]
Okay, here we go.

**Comment by themalkolm** [comment]
:D

**Comment by themalkolm** [comment]
:)

**Comment by iverberk** [comment]
whoops, too fast :-)

**Comment by themalkolm** [comment]
np

**Comment by themalkolm** [comment]
It is working one i.e. https://travis-ci.org/themalkolm/nomad-ui/builds/153385890

**Pull request merged**
