### PR TITLE
Turn NodeID & JobID in allocation/info into links.

### PR DESCRIPTION
**Pull request by themalkolm**

### CODE REVIEW

**Comment by themalkolm** [comment]
We should create NodeID, JobID etc. components so they could be used everywhere instead of making a Link every time.

**Comment by themalkolm** [comment]
Wrong button.

**Comment by themalkolm** [comment]
Any reason this is pending for 7 days?

**Comment by iverberk** [comment]
Sorry, been working on a lot of stuff at the same time.

**Pull request merged**
